### ISSUE TITLE
Exception('Failed to connect to the database after retries')

### ISSUE THREAD

**Issue by TristanThomas03** [LimeDrive/ygg-rss-proxy#27]
Bonjour, j'ai le même message d'erreur que dans le problème rapporté [le 25 juin](https://github.com/LimeDrive/ygg-rss-proxy/issues/25), également avec la version 1.3.3-alpha.
Sur ma machine, ygg-rss-proxy et flaresolverr s'exécutent dans Docker.

Dans ta réponse du 25 juin, de quelle DB parles-tu (je ne suis pas familier avec Docker) ? J'ai un volume nommé "desktop_ygg-rss-proxy-data" que j'ai tenté de supprimer avant de tout réinstaller, il s'est recréé mais j'ai toujours l'erreur.
J'ai octroyé tous les droits avec la commande suivante :

`docker run --rm -v desktop_ygg-rss-proxy-data:/data alpine chmod -R 777 /data`

Mais même erreur.
Voici les logs : [logs.txt](https://github.com/user-attachments/files/16478798/logs.txt)

Merci d'avance !

**Comment by byXav** [comment]
Salut, 

As-tu trouvé la solution ? J'ai le même soucis de base de donnée non accessible. C'est arrivé subitement. J'ai testé sur une autre VM Debian et cela fonctionne, mais pas sur l'ancienne, même en désinstallant-réinstallant complètement Docker. Je ne sais pas ce qui a pu se passer.

**Comment by byXav** [comment]
Je me permets de up, 

J'ai fait ceci : 

Donner pleins droits sur le dossier config sur le host: 
`~/ygg-rss-proxy/config` --> `sudo chmod -R 777 /config`

Donner pleins droits sur la base de données sur le host : 
`~/ygg-rss-proxy/config/rss-proxy.db` --> `sudo chmod 777 rss-proxy.db`

Entrer dans le container pour donner les droits directement : 
`sudo docker exec -it ygg-rss-proxy bash` 

Puis pour les droits : 
`chmod -R 777 config/`
`chmod 777 rss-proxy.db`

Puis redémarrer le container : 
`sudo docker restart ygg-rss-proxy` 

Cela ne fonctionne toujours pas pour ma part. Est-ce que j'ai quelque-chose en plus à faire ? 

Merci ! 
Xav.

**Comment by TristanThomas03** [comment]
> Salut,
> 
> As-tu trouvé la solution ? J'ai le même soucis de base de donnée non accessible. C'est arrivé subitement. J'ai testé sur une autre VM Debian et cela fonctionne, mais pas sur l'ancienne, même en désinstallant-réinstallant complètement Docker. Je ne sais pas ce qui a pu se passer.

Salut, non malheureusement, pas de solution de mon côté. Je vais peut-être essayer sur Debian, mais c'est dommage de changer de VM juste pour ça...
Edit : je viens d'essayer tes différentes commandes pour donner les droits, et ça ne fonctionne pas non plus.

**Comment by LimeDrive** [comment]
Bonjour, 

Navré je ne suis pas trop dispo.

Supprimé la db et relancé le container dans un premier temps.

Si `/config` et monter sur votre système de fichier, le supprimé. ET

stop et del la stack : `docker compose rm -s`
re-up la stack : `docker compose up -d`

Si c'est dans un volume docker : 

stop et del la stack : `docker compose rm -s`
supprimer le volume : `docker volume rm nom_du_volume`
re-up la stack : `docker compose up -d`


Pour débug si jamais il me faudra vos docker-compose que je puisse vérifiez.

**Comment by byXav** [comment]
Salut,

Pas de soucis, t'es pas h24 sur ce projet là et c'est normal ! 

J'ai fait ta manip et ca ne fonctionne pas plus, erreur 500 quand je charge une url, et toujours le problème de bdd dans le log. 

Mon docker-compose comme demandé : https://pastebin.com/K6LQmgZ2

J'ai tenté aussi de rajouter `privileged: true` voir s'il y a une différence mais non. 

Je mets le dernier log de ce matin après suppression et redémarrage : https://pastebin.com/wX4m3HF7

**Comment by LimeDrive** [comment]
> Salut,
> 
> Pas de soucis, t'es pas h24 sur ce projet là et c'est normal !
> 
> J'ai fait ta manip et ca ne fonctionne pas plus, erreur 500 quand je charge une url, et toujours le problème de bdd dans le log.
> 
> Mon docker-compose comme demandé : https://pastebin.com/K6LQmgZ2
> 
> J'ai tenté aussi de rajouter `privileged: true` voir s'il y a une différence mais non.
> 
> Je mets le dernier log de ce matin après suppression et redémarrage : https://pastebin.com/wX4m3HF7

Bon j'ai add du logging sur le version `develop`, je ne peut pas le test directement, merci de le faire et me renvoyé les logs.
https://github.com/LimeDrive/ygg-rss-proxy/pkgs/container/ygg-rss-proxy/256160083?tag=develop
Sa permettra de comprendre pourquoi une exception pass dans la session.

**Je pensait d'ailleurs que flaresolverr était encore down pour le moment ?**

Pour le compose mettre la db dans un volumes, afin d'être sur que sa ne vient pas du montage sur le system : 
```yaml
...
   ygg-rss-proxy:
      image: ghcr.io/limedrive/ygg-rss-proxy:develop
...
         TZ: Europe/Paris
      volumes:
         - proxy-data:/app/config
...

volumes:
   proxy-data: 

```

Vérifiez aussi, vos DNS, des blocage FAI on eue lieux, donc possible de le domaine de ygg ne soit pas accessible depuis votre container.

ajouté les des cloudflare : 


```yaml
      dns:
         - 1.1.1.1
         - 1.0.0.1
```

**Comment by TristanThomas03** [comment]
Merci pour tes réponses !

flaresolverr a eu une période d'arrêt près une mise à jour de cloudflare, mais une solution a été trouvée. J'ai bien le message "problem solved" dans leurs logs.

J'ai testé avec le nouveau docker-compose, je n'ai plus l'erreur de connexion à la DB mais j'en ai une autre...

Voici mon docker-compose :

```
version: '3.8'

services:
   flaresolverr:
      image: ghcr.io/flaresolverr/flaresolverr:pr-1282
      container_name: flaresolverr
      environment:
         LOG_LEVEL: info
         CAPTCHA_SOLVER: none
         TZ: Europe/Paris
      expose:
        - 8191
      restart: unless-stopped

   ygg-rss-proxy:
      image: ghcr.io/limedrive/ygg-rss-proxy:develop
      container_name: ygg-rss-proxy
      environment:
         YGG_USER: <MON USER>
         YGG_PASS: <MON PASS>
         RSS_HOST: localhost
         RSS_PORT: 5000
         FLARESOLVERR_HOST: flaresolverr
         LOG_LEVEL: INFO
         TZ: Europe/Paris
      volumes:
         - proxy-data:/app/config
      ports:
         - 5000:8080
      restart: unless-stopped
      depends_on:
         - flaresolverr

volumes:
   proxy-data:
```

J'ai essayé avec les DNS, mais même erreur.

Et voici mes logs : [logs.txt](https://github.com/user-attachments/files/16574348/logs.txt)

Merci d'avance pour ton aide !
