### ISSUE TITLE
Proxy ne renvoi pas les challenges à Flaresolver

### ISSUE THREAD

**Issue by molotovah** [LimeDrive/ygg-rss-proxy#29]
J'utilise [Gluetun](https://github.com/qdm12/gluetun), un container docker embarquant un VPN qui permet de cacher le trafic des autres container derrière un VPN. 

Sans le proxy YGG, ça fonctionne correctement , (Flaresolver résout les requêtes de Jackett).

Le problème rencontré est que je ne vois pas les demandes de challenge issues de YGG Proxy arriver dans Flaresolver

**Erreur rencontrée**
[ygg-rss-proxy-2024-10-12T17-16-43.log](https://github.com/user-attachments/files/17350901/ygg-rss-proxy-2024-10-12T17-16-43.log)

**Mon docker-compose**
```yaml
networks:
  tunnel:
    external: true
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN # Ajoute les capacités nécessaires pour gérer les interfaces réseau
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp   # HTTP proxy
      - 8388:8388/tcp   # Shadowsocks TCP
      - 8388:8388/udp   # Shadowsocks UDP
      - 9117:9117       # Port pour Jackett
      - 8080:8080       # Port pour Ygg-RSS
      - 8191:8191       # Port pour FlareSolverr
      - 44587:44587     # Port pour Joal
      - 1080:1080       # Proxy Socks5 pour QBittorrent
      - 6881:6881/udp   # Port UDP pour le téléchargement de torrents
      - 9080:9080       # Interface web de QBittorrent
      - 9566:9566/udp   # Port UDP pour QBittorrent
    volumes:
      - /home/user/docker-data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=XXXXXXXXXXXXXXXXXXXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXX
      - SERVER_REGIONS=Europe
      - SERVER_CATEGORIES=P2P
      - TZ=Europe/Paris
      - UPDATER_PERIOD=24h
    restart: always
    networks:
      - tunnel
  # Service Ygg-RSS Proxy : Pour les flux RSS protégés
  ygg-rss-proxy:
    image: ghcr.io/limedrive/ygg-rss-proxy:latest
    container_name: ygg-rss-proxy
    environment:
       TZ: Europe/Paris
       YGG_USER: 'XXXXXXXXXXXXXXXXXXXXXXXX'
       YGG_PASS: 'XXXXXXXXXXXXXXXXXXXXXXXX'
       FLARESOLVERR_HOST: gluetun
       FLARESOLVERR_SHEMA: http
       FLARESOLVERR_PORT: 8191
       RSS_HOST: gluetun
       RSS_PORT: 8080
       LOG_LEVEL: INFO
    volumes:
       - /home/user/docker-data/ygg-rss/config:/app/config
    restart: unless-stopped
    network_mode: "service:gluetun" # Utilise le réseau de Gluetun
    depends_on:
      gluetun:
        condition: service_healthy # Démarre lorsque Gluetun est sain
      flaresolverr:
        condition: service_started
  # Service FlareSolverr : Pour contourner les captchas
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    restart: unless-stopped 
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
  # Service Jackett : Agrégateur de moteurs de recherche de torrents
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true
      - RUN_OPTS= # Optionnel
    volumes:
      - /home/user/docker-data/jackett/config:/config
      - /mnt/data/Torrents/watch:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"    
    depends_on:
      gluetun:
        condition: service_healthy
  # Service Joal : Simulateur de partage pour les torrents
  joal:
    image: anthonyraymond/joal:latest
    container_name: joal
    volumes:
      - /home/user/docker-data/joal:/data
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=44587", "--joal.ui.path.prefix=****", "--joal.ui.secret-token=****"]
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
  # Service QBittorrent : Client torrent
  qbittorrent:
    image: "linuxserver/qbittorrent:latest"
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=9080
      - TORRENTING_PORT=6881
    volumes:
      - /home/user/docker-data/qbittorrent/config:/config
      - /home/user/docker-data/qbittorrent/plugins:/plugins
      - /mnt/data/Torrents/downloads:/downloads
      - /mnt/data/Torrents/watch:/watch
      - /mnt/data/Torrents/Torrent_Files:/torrent   
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
```

Merci de votre aide
