### ISSUE TITLE
error : "Failed to retrieve RSS feed" with the new version 1.0.0-alpha

### ISSUE THREAD

**Issue by byXav** [LimeDrive/ygg-rss-proxy#9]
Bonjour, 

J'ai voulu tester la nouvelle version ce soir, mais après essais j'obtiens une erreur pour récupérer le flux RSS. 

Ci joint le log : 

`2024-06-11T19:20:42.118581+0000 INFO ----------------------------------------------------------`
`2024-06-11T19:20:42.118953+0000 INFO Checking directories...`
`2024-06-11T19:20:42.119199+0000 INFO ----------------------------------------------------------`
`2024-06-11T19:20:42.119583+0000 INFO Directory /app/config already exists.`
`2024-06-11T19:20:42.119892+0000 INFO Directory /app/config/rss-proxy.db already exists.`
`2024-06-11T19:20:42.120400+0000 INFO Directory /app/config/rss-proxy.db already exists.`
`2024-06-11T19:20:42.120750+0000 INFO ----------------------------------------------------------`
`2024-06-11T19:20:42.120897+0000 INFO Starting ygg_rss_proxy on http://192.168.1.133:8080`
`2024-06-11T19:20:42.121042+0000 INFO ----------------------------------------------------------`
`2024-06-11T19:21:08.543761+0000 DEBUG Starting new HTTPS connection (1): www.ygg.re:443`
`2024-06-11T19:21:08.655916+0000 DEBUG https://www.ygg.re:443 "GET /auth/login HTTP/1.1" 403 None`
`2024-06-11T19:21:08.659769+0000 INFO Cloudflare is enabled, using FlareSolverr`
`2024-06-11T19:21:08.664042+0000 DEBUG Starting new HTTP connection (1): 192.168.1.133:8191`
`2024-06-11T19:21:08.671207+0000 DEBUG http://192.168.1.133:8191 "GET / HTTP/1.1" 200 172`
`2024-06-11T19:21:10.024198+0000 DEBUG http://192.168.1.133:8191 "POST /v1 HTTP/1.1" 200 1016`
`2024-06-11T19:21:10.025217+0000 INFO Successfully authenticated to YGG`
`2024-06-11T19:21:10.025494+0000 DEBUG Cloudflare cookies: []`
`2024-06-11T19:21:10.026361+0000 DEBUG Resetting dropped connection: www.ygg.re`
`2024-06-11T19:21:10.101604+0000 DEBUG https://www.ygg.re:443 "POST /auth/process_login HTTP/1.1" 403 None`
`2024-06-11T19:21:10.102362+0000 DEBUG Session cookies: <CookieJar[]>`
`2024-06-11T19:21:10.103484+0000 DEBUG Starting new HTTPS connection (1): www.ygg.re:443`
`2024-06-11T19:21:10.178111+0000 DEBUG https://www.ygg.re:443 "GET /rss?action=generate&type=cat&id=2145&passkey=##### HTTP/1.1" 403 None`
`2024-06-11T19:21:10.179971+0000 INFO Session may have expired, re-authenticating...`
`2024-06-11T19:21:10.181992+0000 DEBUG Resetting dropped connection: www.ygg.re`
`2024-06-11T19:21:10.262328+0000 DEBUG https://www.ygg.re:443 "GET /auth/login HTTP/1.1" 403 None`
`2024-06-11T19:21:10.264591+0000 INFO Cloudflare is enabled, using FlareSolverr`
`2024-06-11T19:21:10.267536+0000 DEBUG Starting new HTTP connection (1): 192.168.1.133:8191`
`2024-06-11T19:21:10.275946+0000 DEBUG http://192.168.1.133:8191 "GET / HTTP/1.1" 200 172`
`2024-06-11T19:21:11.601602+0000 DEBUG http://192.168.1.133:8191 "POST /v1 HTTP/1.1" 200 1016`
`2024-06-11T19:21:11.602054+0000 INFO Successfully authenticated to YGG`
`2024-06-11T19:21:11.602219+0000 DEBUG Cloudflare cookies: []`
`2024-06-11T19:21:11.602848+0000 DEBUG Resetting dropped connection: www.ygg.re`
`2024-06-11T19:21:11.684934+0000 DEBUG https://www.ygg.re:443 "POST /auth/process_login HTTP/1.1" 403 None`
`2024-06-11T19:21:11.695937+0000 DEBUG Session cookies: <CookieJar[]>`
`2024-06-11T19:21:11.699395+0000 DEBUG Resetting dropped connection: www.ygg.re`
`2024-06-11T19:21:11.781656+0000 DEBUG https://www.ygg.re:443 "GET /rss?action=generate&type=cat&id=2145&passkey=##### HTTP/1.1" 403 None`

De ce que je comprends pour l'instant il parvient à se connecter, mais il bute sur le RSS, qu'il n'arrive pas à récupérer. 

Je mets mon docker-compose.yaml au cas où : 

`services:`
`  ygg-rss-proxy:`
`      image: ghcr.io/limedrive/ygg-rss-proxy:v1.0.0-alpha`
`      container_name: ygg-rss-proxy`
`      ports:`
`         - "8080:8080"`
`      #expose:`
`         #- 5000`
`      environment:`
`         YGG_USER: "UTILISATEUR"`
`         YGG_PASS: "MOTDEPASSE"`
`         YGG_URL: 'https://www.ygg.re'`
`         RSS_HOST: '192.168.1.133'`
`         RSS_PORT: '8080'`
`         FLARESOLVERR_HOST: '192.168.1.133'`
`         FLARESOLVERR_PORT: '8191'`
`         LOG_LEVEL: INFO`
`      volumes:`
`         - /home/xavier/docker/ygg-rss-proxy/config:/app/config`
`      restart: unless-stopped`
`      depends_on:`
`         - flaresolverr`

`  flaresolverr:`
`      image: ghcr.io/flaresolverr/flaresolverr:latest`
`      container_name: flaresolverr`
`      environment:`
`         LOG_LEVEL: info`
`         CAPTCHA_SOLVER: none`
`      ports:`
`         - "8191:8191"`
`      #expose:`
`         #- 8191`
`      restart: unless-stopped`

Dans le log ygg-rss-proxy sur Portainer j'ai l'erreur suivante aussi : 

`/usr/local/lib/python3.11/site-packages/pydantic_settings/sources.py:431: UserWarning: directory "/run/secrets" does not exist`
`  warnings.warn(f'directory "{self.secrets_path}" does not exist')`
...
...
`2024-06-11T19:32:18.827802+0000 INFO Cloudflare is enabled, using FlareSolverr`
`2024-06-11T19:32:20.331897+0000 INFO Successfully authenticated to YGG`

Mais apparemment sans incidence vu que la fin du log indique qu'il réussi à se connecter. 

Est-ce que c'est comme l'autre fois et il faut attendre d'avoir une autre plage d'IP dès fois que le bot les ait "repérées" ou j'ai un soucis quelque-part de mon côté ? JE ne comprends pas pourquoi il ne parvient pas à récupérer le flux. 
J'ai tenté de le lancer sur une autre VM en simplifiant mon docker-compose.yaml mais j'obtiens le même résultat. 

Merci. 

Xavier.

**Comment by LimeDrive** [comment]
Bonjour,

Je déconseille d'exposer FlareSolverr, ce n'est pas nécessaire pour le fonctionnement. Et le souci peut se poser que si jamais ton endpoint est trouvé, on peut très vite l'overload. 

```yaml
services:
  ygg-rss-proxy:
      image: ghcr.io/limedrive/ygg-rss-proxy:v1.0.0-alpha
      container_name: ygg-rss-proxy
      ports:
         - "8080:8080"
      environment:
         YGG_USER: "UTILISATEUR"
         YGG_PASS: "MOTDEPASSE"
         RSS_HOST: '192.168.1.133'
         FLARESOLVERR_HOST: 'flaresolverr'
         LOG_LEVEL: INFO
      volumes:
         - /home/xavier/docker/ygg-rss-proxy/config:/app/config
      restart: unless-stopped
      depends_on:
         - flaresolverr

  flaresolverr:
      image: ghcr.io/flaresolverr/flaresolverr:latest
      container_name: flaresolverr
      environment:
         LOG_LEVEL: info
         CAPTCHA_SOLVER: none
      expose:
         - "8191"
      restart: unless-stopped
```

```
2024-06-11T19:21:08.671207+0000 DEBUG http://192.168.1.133:8191 "GET / HTTP/1.1" 200 172
2024-06-11T19:21:10.024198+0000 DEBUG http://192.168.1.133:8191 "POST /v1 HTTP/1.1" 200 1016
2024-06-11T19:21:10.025217+0000 INFO Successfully authenticated to YGG
2024-06-11T19:21:10.025494+0000 DEBUG Cloudflare cookies: []
2024-06-11T19:21:10.026361+0000 DEBUG Resetting dropped connection: www.ygg.re
2024-06-11T19:21:10.101604+0000 DEBUG https://www.ygg.re:443 "POST /auth/process_login HTTP/1.1" 403 None
2024-06-11T19:21:10.102362+0000 DEBUG Session cookies: <CookieJar[]>
```
il y a effectivement un mauvais retour de Flaresolverr, comme d'hab sa dépend des IP. Je vais revoir un peu le log pour le signaler plus clairement. Attendre est une solution qui fonctionne parfois.
